version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: deployment/api/Dockerfile
    container_name: ml-api
    ports:
      - "8000:8000"
    restart: always

  app:
    build:
      context: ../
      dockerfile: deployment/app/Dockerfile
    container_name: ml-app
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always
    